### ISSUE TITLE
People Picker unselects pods on initial render

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#1040]
In staging if you open the people picker and immediately start selecting people after a second they become unselected. Is this a race condition with onSave?

**Comment by Cooryd** [comment]
Planned solution: 
- refactor PeoplePicker to take an onChange prop instead of setSelectedPeople & onRemove(?) 
- move selectedPeople into the PeoplePicker component as state and set initially to `initialSelected` prop.
- onDone and onRemove for PeoplePicker sub components to be replaced with new local functions that call both setState and the onChange callback to update local selectedPeople state and push that change up to the parent component.
