### ISSUE TITLE
Incident 120452144 OPENED: 'elife-xpub--prod--1' 'host not reporting

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#704]
Occurred over the weekend - see https://infrastructure.newrelic.com/accounts/1451451/events?filters=%7B%22and%22%3A%5B%7B%22is%22%3A%7B%22entityName%22%3A%22elife-xpub--prod--1%22%7D%7D%5D%7D&timeEnd=1586104875721&timeStart=1586101275721

**Comment by diversemix** [comment]
Discussion happening here: 
https://elifesciences.slack.com/archives/C6LKMFK5Z/p1586158030000700

Summary is that sciencebeam ran out of memory - There were 3 simultaneous uploads of the same manuscript happening simultaneously.

**Comment by diversemix** [comment]
### Apr  5 
16:05:46 - Manuscript a3be6e2e saved
16:05:49 - Manuscript a3be6e2e saved
16:05:51 - Manuscript a3be6e2e saved
16:05:51 - Semantic extraction started....
16:05:45 - Sciencebeam crashed - kill process initiated 
16:12:23 - tini invoked oom-killer 
16:12:23 - oom_reaper: reaped process

**Comment by diversemix** [comment]
There are only 2 manuscripts saved for `a3be6e2e-a689-44bb-aa79-53b702317c50` in s3, both of which have the same checksum.

- s3://prod-elife-xpub/manuscripts/a3be6e2e-a689-44bb-aa79-53b702317c50/ed596cad-7b6d-4580-b297-16905a4c95eb
- //prod-elife-xpub/manuscripts/a3be6e2e-a689-44bb-aa79-53b702317c50/0a2c2bc9-d945-4ec7-803a-2095ba5dda71

**Comment by diversemix** [comment]
Going to pause work on this - @de-code has reported that the demo site has issues with this as it is large (561 pages + HQ images)

/cc @hdrury1

**Comment by de-code** [comment]
The [demo site](https://sciencebeam-texture.elifesciences.org/) has a limit on the file size that can be uploaded.

```console
$curl --fail --show-error --form "file=@/path/to/ed596cad-7b6d-4580-b297-16905a4c95eb.pdf;filename=ed596cad-7b6d-4580-b297-16905a4c95eb.pdf" \
  https://sciencebeam-texture.elifesciences.org/api/convert
curl: (22) The requested URL returned error: 413 Request Entity Too Large
```

I will check where that is configured.

**Comment by de-code** [comment]
Just to confirm, the maximum file size for xPub is 100 MB?

**Comment by de-code** [comment]
After increasing the limit locally I am getting this from GROBID:

```
grobid_1               | ERROR [2020-04-06 11:05:02,738] org.grobid.core.process.ProcessPdf2Xml: pdftoxml process finished with error code: 143. [/opt/grobid/grobid-home/pdf2xml/lin-64/pdftoxml_server, -blocks, -noImageInline, -fullFontName, -noImage, -annotation, /opt/grobid/grobid-home/tmp/origin3676747084546722751.pdf, /opt/grobid/grobid-home/tmp/2eEcMeSu3H.lxml]
grobid_1               | ERROR [2020-04-06 11:05:02,744] org.grobid.core.process.ProcessPdf2Xml: pdftoxml return message: 
grobid_1               | Error: Illegal entry in bfchar block in ToUnicode CMap
grobid_1               | 
grobid_1               | ERROR [2020-04-06 11:05:02,872] org.grobid.service.process.GrobidRestProcessFiles: An unexpected exception occurs. 
grobid_1               | ! org.grobid.core.exceptions.GrobidException: [TIMEOUT] PDF to XML conversion timed out
grobid_1               | ! at org.grobid.core.document.DocumentSource.processPdf2XmlServerMode(DocumentSource.java:223)
```

On a second attempt I was lucky to receive another error:

```
grobid_1               | ERROR [2020-04-06 11:09:52,222] org.grobid.service.process.GrobidRestProcessFiles: An unexpected exception occurs. 
grobid_1               | ! org.grobid.core.exceptions.GrobidException: [TOO_MANY_TOKENS] The document has 1178820 tokens, but the limit is 1000000
grobid_1               | ! at org.grobid.core.engines.Segmentation.prepareDocument(Segmentation.java:126)
grobid_1               | ! at org.grobid.core.engines.Segmentation.processing(Segmentation.java:95)
```

The later can be configured I believe.

**Comment by de-code** [comment]
I am not sure how to best move forward as there seem to be a few potential issues:
- The issue raised was related to a memory issue:
  - I can't reproduce that but haven't tried to upload multiple documents. In any case it depends on the VM configuration. A solution could be to simply increase the available memory.
- The current GROBID configuration would reject that particular document because there too many tokens:
  - The configuration could be updated (with the current GROBID version a file would need to be mounted, with my fork it could be changed via an environment variable)
- There are potential timeouts:
  - There are timeouts within GROBID (some may not even be configurable at present)
  - xPub itself has a timeout
  - A larger document generally requires more time to process. GROBID has the option to only process the first three pages. But I found that to be less accurate (as it also skips some processing), it would be faster though and may also address the too many token issue above.
  - An option would be to accept that and only look at the first few pages, or do that if the file exceeds a certain size

**Comment by diversemix** [comment]
Thanks for the input @de-code 

I've also tested on staging a couple of times and cannot get it to crash ... but it didn't suggest a title (as expected for this doc)

@hdrury1 ... The failure case is that the user does not get the title field populated. However, for whatever reason there was an out-of-memory error that took down the server for a few minutes. As @de-code mentions we can always increase the available memory if it happens again in the future.

I'm closing this out for now.

/cc @erkannt (just in way of FYI in case you have any ideas of isolating sciencebeam from the rest of the app)
