### ISSUE TITLE
Apply memory limits on sciencebeam

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#714]
Following https://github.com/libero/reviewer/issues/704

We have decided to introduce memory limits. Investigate with @de-code and apply to any container we use.

**Comment by erkannt** [comment]
This appears to be less straightforward than hoped:

- since docker-compose v3 `resources` setting have been moved into the `deploy` section
- `deploy` is only understood by docker swarm (which we don't use)
- checking memory usage from within the container is [possible](https://shuheikagawa.com/blog/2017/05/27/memory-usage/) but [not standardized](https://fabiokung.com/2014/03/13/memory-inside-linux-containers/)
- `--compatibility` flag can be used to make make docker compose understand `deploy` but not recommended for production

Is there something aside from memory usage that we can use to `healthcheck` sciencebeam in a way that ensures we fail fast and avoid cascading issues? Or maybe even have sciencebeam fail itself? @de-code ?

**Comment by de-code** [comment]
> Is there something aside from memory usage that we can use to `healthcheck` sciencebeam in a way that ensures we fail fast and avoid cascading issues? Or maybe even have sciencebeam fail itself? @de-code ?

There should already be healthchecks in the form of port polling (unless it's not in the xPub docker-compose config). I am not sure whether you meant that. What did you have in mind?

Was it actually the `sciencebeam` or the `grobid` container that was killed?

**Comment by erkannt** [comment]
The polling healthchecks are in place. I was just wondering if we could think of something that could react quicker to an issue inside sciencebeam.

According to Peter's digging it was sciencebeam that crashed: https://github.com/libero/reviewer/issues/704#issuecomment-609661465

If you also can't think of an easy way to make the container fail faster I'd suggest closing this and keep it in mind should we move this stack to a k8s cluster.

**Comment by de-code** [comment]
> According to Peter's digging it was sciencebeam that crashed: [#704 (comment)](https://github.com/libero/reviewer/issues/704#issuecomment-609661465)

GROBID may be seen as part of ScienceBeam in general. I believe the `sciencebeam` container doesn't use `tini` but GROBID does. That's why I thought it might actually have been the `grobid` container.

> If you also can't think of an easy way to make the container fail faster I'd suggest closing this and keep it in mind should we move this stack to a k8s cluster.

I don't have a good idea. There is certainly something within `sciencebeam` that could be refactored to use less memory by using the disk more. It could also check the file size (but so could xPub before sending it). i.e. I don't really have a good idea. It should however recover from a crash.

**Comment by erkannt** [comment]
Ok. Then I'm closing this.
