### ISSUE TITLE
Initiate discussion on Browser / OSes support and choose a test bed for these

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#839]
@hdrury1  confirm on this ticket.
Involved @davidcmoulton in any decision taken for test bed.

**Comment by hdrury1** [comment]
Top 5 browsers, last 30 days

<img width="362" alt="Screenshot 2020-05-04 at 12 45 34" src="https://user-images.githubusercontent.com/17023702/80962640-4ca3b800-8e05-11ea-8d8a-d48cabb10e51.png">

Previous 30 days

<img width="364" alt="Screenshot 2020-05-04 at 12 47 24" src="https://user-images.githubusercontent.com/17023702/80962697-6cd37700-8e05-11ea-9fe7-6947fdd831e4.png">

Previous 12 months

<img width="371" alt="Screenshot 2020-05-04 at 12 48 20" src="https://user-images.githubusercontent.com/17023702/80962760-8eccf980-8e05-11ea-9b5b-74a7a014eaed.png">

We should test against all of these (i.e. those browsers that 2% or more of our current users are using).

**Comment by erkannt** [comment]
So this means: Chrome, Safari, Firefox, Edge and Internet Explorer? Or no IE as it dropped below 2% this month?

Open questions for me would be:
- Do we test only against the latest version of each browser?
- Does the OS matter e.g. we run Chrome/FF on Linux only?

**Comment by hdrury1** [comment]
Hi @erkannt. We should support Chrome, Safari, Firefox, Edge and IE yes.

As for supporting legacy versions of browsers... I'd be keen to hear thoughts from @chugginselifesciences on this point.

How does the OS affect browser behaviour? I would be testing on Windows and Mac- very few of our users are using Linux.

**Comment by chugginselifesciences** [comment]
I'll have to look at this a little later I'm afraid. Do you remember what versions we decided to support for xPub? I would imagine it makes sense to support the same as the journal.

**Comment by chugginselifesciences** [comment]
@hdrury1 I always struggle with this question to be honest because from a UX perspective the answer would be to support as much as possible. But it has to be weighed against effort. I expect we would rely on the tech team to know which aspects of Reviewer might be supported by only the newer browsers/supported the least by older browsers. And judge the importance of them vs. the % of people using them. Do they prevent people submitting, or is it less problematic etc.

With IE for example I believe we were just aiming for xPub to be as usable as possible without spending too much time on it, but it's not really practical to get the experience to match that of latest Chrome, Firefox etc.

We could look into analytics for browser versions maybe? But I think it makes more sense to see where it fails badly and how many users it would affect. Assuming we can do that using browser stack?

**Comment by hdrury1** [comment]
Thanks Chris. I understand @davidcmoulton may have some really helpful advice on supporting legacy browsers. David, are you able to weigh in when you get a chance this week?

**Comment by davidcmoulton** [comment]
## PC / Mac / *nix browsers

### Evergreen browsers (Chrome, Firefox, Edge)

It's okay to test only on the latest version of each: if someone's prevented from updating an evergreen browser, they've got bigger problems.

These days I'd say it's safely pragmatic to only test on one platform. It's been years since I last came across a bug that manifested or manifested differently in identical browser versions on different platforms.

### Safari
It's worth breaking down the Safari stats, as Safari is pretty tied to OSX version and so isn't evergreen. You might need to test on a few Safari versions, depending on what the breakdown looks like.

### IE
It may only be responsible for 1.5%-2% of the traffic, but these are likely to be users who are unable to update their browser or use an alternative, since if they could, they likely would. Abandoning them completely seems wrong to me.

Keep in mind the mantra that "it doesn't have to look / behave the same in every browser". One option is to give IE a different set of tests: work out what the minimal acceptable testable functionality is, and test only for that in IE. Depending on how the tests are written, it might be feasible that these base-level tests could be incorporated as a subset of the test suites for the other browsers, meaning less duplication.

## Mobile browsers
"Mobile" here means any platform smaller than a laptop, typically a tablet or phone.

I don't see any stats for mobile browsers in this ticket. Not sure if that's because no-one submits on anything smaller than a laptop, it's out of scope for this ticket, or it's not a product requirement. 

Online services like Browserstack give you the ability to test on real mobile devices as part of your CI tests (manually too, if you want to). This could be a rabbit hole without stats to guide you. Even if there are no submissions coming in via mobile at the moment, I'd still test on a minimal set (the overall most popular Android phone in the target regions, latest iPad, latest iPhone), not least because then you can rule out the lack of stats for mobile being down to critical failure on mobile. It also guards against the scenario of suddenly finding out about a slew of mobile browser bugs from users when there's sudden uptake on mobile, bugs you didn't know about because you're not testing on mobile, because until last week the numbers were too low...

Let me know if there's anything I've missed, or anything else you want to consider. Happy to discuss further.

**Comment by hdrury1** [comment]
Meeting scheduled 19/5

**Comment by davidcmoulton** [comment]
# Decisions

- Test on the latest respective versions of Chrome and Firefox in Linux.
- (Browserstack) Test on MS Edge 18 (last Spartan Edge version), and latest Edge Anaheim (Chromium version, 81.x.x at the time of writing). Monitor Edge 18 use and test until below support threshold.
- (Browserstack) Test on Safari versions 13.1 (Catalina), 12.1 (Mojave) and 11.1 (High Sierra). Monitor Safari usage stats and add / remove versions for support & testing as Safari evolves.
- (Browserstack) Decision deferred on whether to support IE (and so make to make it work in IE, and institute IE testing). Unknown how much work it would be to make it work in IE. Discovery around this may help decide whether support it or not. Consider whether stats are above support threshold before deciding.
- (Browserstack) Support mobile, but no testing yet. When decided to test on mobile, examine stats for device / browser profile to test on. Sensible default if no meaningful stats is the overall most popular Android phone in the target regions, latest iPad, latest iPhone.
- First step: add Firefox on Linux to the browser test set, where it joins Chrome.

# Questions
- what should the support threshold be?
- when to consider IE support?
- when to institute mobile testing?
- how to document the decisions and outstanding questions in this ticket?
